### PR TITLE
Use generator.throw to fix generator error raising.

### PR DESCRIPTION
**Pull request by phillbaker**
Closes https://github.com/danielfm/pybreaker/issues/47, more details there.

### CODE REVIEW

**Comment by phillbaker** [comment]
Looks like the build failures were on python 3.2 and 3.3 (same as what's on master). (I think those versions are end-of-life'd as well.)

**Comment by phillbaker** [comment]
@danielfm any thoughts here?

**Comment by phillbaker** [comment]
Thanks! Any chance you can release a new version with this?

**Comment by danielfm** [comment]
Released. Sorry for the delay.

**Pull request merged**
