### PR TITLE
Add linter & format setup

### PR DESCRIPTION
**Pull request by Kludex**
# Changes
- Add `pre-commit` configuration file.
- Add [`isort`](https://pycqa.github.io/isort/) to sort import statements.
- Add [`black`](https://github.com/psf/black) to format code.
- Remove `#-*- coding:utf-8 -*-` because it's not needed anymore.

### CODE REVIEW

**Comment by danielfm** [comment]
@Kludex the `coding:utf-8` comments are still there though. Which is outdated, the code or the PR description?

**Comment by Kludex** [comment]
The code. I forgot to push... 🤦

**Comment by Kludex** [comment]
Done 👍

**Comment by danielfm** [comment]
Thanks!

**Pull request merged**
