### PR TITLE
Improve type annotation on `CircuitBreakerState`

### PR DESCRIPTION
**Pull request by Kludex**
I'd like to add type annotation on the whole module. Would you mind? Python 3.6 supports it just fine. 😗

### CODE REVIEW

**Comment by danielfm** [comment]
I'm not familiar with this, not really working with Python anymore, so pretty sure there are lots of new language features I'm not aware.

I'll take a look into this.

Thanks for the contributions you've made!

**Comment by danielfm** [comment]
Can you rebase this with the current `master` branch? Just as a final check before merging.

**Comment by Kludex** [comment]
Done 👍

**Comment by danielfm** [comment]
Thanks!

**Pull request merged**
